export const ALL_PRODUCTS = [
  { 
    id: '1', 
    name: 'Zenitsu Lightning Drop-Shoulder Tee', 
    price: 1099, 
    originalPrice: 1599, 
    badge: 'BEST SELLER', 
    graphicColor: '#D4FF00', 
    category: 'Anime', 
    sizes: ['M', 'L', 'XL'], 
    rating: 4.9, 
    reviewsCount: 154, 
    image: '/images/11_17386de2-0138-468a-b616-8019451fa26b.webp',
    description: 'Black drop-shoulder streetwear tee featuring a high-density Zenitsu visual on the back with detailed lightning graphics in neon volt yellow. Heavyweight 240 GSM built for durability.'
  },
  { 
    id: '2', 
    name: 'Gas Mask Shinigami Cream Tee', 
    price: 1099, 
    originalPrice: 1599, 
    badge: 'NEW DROP', 
    graphicColor: '#E5D3B3', 
    category: 'Anime', 
    sizes: ['S', 'M', 'L', 'XL'], 
    rating: 4.8, 
    reviewsCount: 88, 
    image: '/images/zoom_0-1739428581.avif',
    description: 'Cream white oversized tee featuring a detailed graphic of a shinigami clad in a modern gas mask and urban streetwear. Direct-to-garment premium print.'
  },
  { 
    id: '3', 
    name: 'Anime Eyes Multicharacter Tee', 
    price: 999, 
    originalPrice: 1499, 
    badge: 'POPULAR', 
    graphicColor: '#FFB7C5', 
    category: 'Anime', 
    sizes: ['M', 'L', '2XL'], 
    rating: 5.0, 
    reviewsCount: 92, 
    image: '/images/8_b3650bcd-7a35-4191-bda0-9b4e526329de.webp',
    description: 'Baby pink streetwear tee. A multicharacter collage of iconic anime eyes printed in rich, high contrast colorways across the front chest panel.'
  },
  { 
    id: '4', 
    name: 'Graffiti Teddy Streetwear Tee', 
    price: 1099, 
    originalPrice: 1599, 
    badge: '10% OFF', 
    graphicColor: '#0D0D0D', 
    category: 'Graphic', 
    sizes: ['S', 'M', 'XL', '2XL'], 
    rating: 4.7, 
    reviewsCount: 112, 
    image: '/images/Artboard_5_1_2.webp',
    description: 'Pitch black drop-shoulder shirt containing a distressed graffiti teddy bear graphic on the front, overlayed with hyper-detailed typography.'
  },
  { 
    id: '5', 
    name: 'Yuta & Rika Cursed Energy Tee', 
    price: 1099, 
    originalPrice: 1699, 
    badge: '', 
    graphicColor: '#F3F4F6', 
    category: 'Anime', 
    sizes: ['S', 'M', 'L'], 
    rating: 4.6, 
    reviewsCount: 45, 
    image: '/images/81ofupTz8TL._AC_UY1100_.jpg',
    description: 'Grey-white oversized comfort shirt depicting Yuta Okkotsu and the manifestation of special grade vengeful cursed spirit Rika Orimoto.'
  },
  { 
    id: '6', 
    name: 'Cybernetic Exoskeleton Spine Tee', 
    price: 1199, 
    originalPrice: 1799, 
    badge: 'FUTURE', 
    graphicColor: '#3B82F6', 
    category: 'Graphic', 
    sizes: ['M', 'L', 'XL', '2XL'], 
    rating: 4.8, 
    reviewsCount: 57, 
    image: '/images/edit-kj-v-7.webp',
    description: 'Royal cobalt blue print on black core tee. Showcases a highly detailed mechanical cybernetic spine running down the length of the back panel.'
  },
  { 
    id: '7', 
    name: 'Love With No Limits Tropical Tee', 
    price: 999, 
    originalPrice: 1399, 
    badge: '', 
    graphicColor: '#1B4332', 
    category: 'Minimalist', 
    sizes: ['S', 'M', 'L', 'XL'], 
    rating: 4.9, 
    reviewsCount: 73, 
    image: '/images/1781935523397-eaa6b2865a45441a-DA13E7C1884FE912E711D3FFB60D9AA2.webp',
    description: 'Forest green minimalist streetwear tee with a small chest print featuring retro font styling and tropical palm silhouettes.'
  },
  { 
    id: '8', 
    name: 'Vaporwave Skull Sneaker Tee', 
    price: 999, 
    originalPrice: 1499, 
    badge: 'POPULAR', 
    graphicColor: '#0D0D0D', 
    category: 'Minimalist', 
    sizes: ['M', 'L', 'XL'], 
    rating: 4.7, 
    reviewsCount: 81, 
    image: '/images/Oversize_Back_Printed_oversize_t_shirt_for_men_-_FastColors_-_Oversize_Back_Printed_T-Shirt_-_FastColors_-_tag1_-_tag2_-_tag3_-_-6266647.webp',
    description: 'Off-black oversized tee with vaporwave design aesthetics, combining a classic skull design with vibrant retro sneaker overlays.'
  },
  { 
    id: '9', 
    name: 'Woops Stay Sick Cartoon Tee', 
    price: 999, 
    originalPrice: 1499, 
    badge: '', 
    graphicColor: '#FF2E23', 
    category: 'Graphic', 
    sizes: ['S', 'M', 'L', 'XL'], 
    rating: 4.5, 
    reviewsCount: 38, 
    image: '/images/Artboard25_74.webp',
    description: 'Vibrant red cartoon skull print on a black drop-shoulder. Standard high density screen printed details.'
  },
  { 
    id: '10', 
    name: 'Break the Rules Distressed Tee', 
    price: 999, 
    originalPrice: 1499, 
    badge: 'POPULAR', 
    graphicColor: '#0D0D0D', 
    category: 'Graphic', 
    sizes: ['M', 'L', 'XL', '2XL'], 
    rating: 4.6, 
    reviewsCount: 64, 
    image: '/images/Black_Printed_oversize_t_shirt_for_men_-_FastColors_-_Oversize_Printed_T-Shirt_-_FastColors_-_tag1_-_tag2_-_tag3_-_-6265988.webp',
    description: 'Heavyweight black tee with high contrast white text in distressed gothic calligraphy layout reading Break the Rules across the chest.'
  },
  { 
    id: '11', 
    name: 'Retro SWAG Pop-Art Collage Tee', 
    price: 1099, 
    originalPrice: 1599, 
    badge: '', 
    graphicColor: '#0D0D0D', 
    category: 'Graphic', 
    sizes: ['M', 'L', 'XL'], 
    rating: 4.8, 
    reviewsCount: 51, 
    image: '/images/b_0119493a-9927-4550-8323-baefe5f625c0.webp',
    description: 'A pop-art inspired retro design featuring collage graphics and typography overlays on a standard heavy drop-shoulder structure.'
  },
  { 
    id: '12', 
    name: 'Berserk Menace Screaming Tee', 
    price: 1199, 
    originalPrice: 1799, 
    badge: 'HOT DROP', 
    graphicColor: '#3B82F6', 
    category: 'Graphic', 
    sizes: ['S', 'M', 'L', 'XL', '2XL'], 
    rating: 4.9, 
    reviewsCount: 118, 
    image: '/images/Berserking-Menace-7.webp',
    description: 'Hyper-detailed graphic of Guts in his berserker armor printed in high contrast blue and white scale across the back of a premium black tee.'
  },
  { 
    id: '13', 
    name: 'Monkey D. Luffy Gear 5 Tee', 
    price: 1099, 
    originalPrice: 1699, 
    badge: 'BEST SELLER', 
    graphicColor: '#D4FF00', 
    category: 'Anime', 
    sizes: ['M', 'L', 'XL', '2XL'], 
    rating: 4.9, 
    reviewsCount: 210, 
    image: '/images/fsguc_512.webp',
    description: 'Volt yellow highlights on Luffy in his mythical Sun God Nika (Gear 5) form. A stunning streetwear visual printed on premium 240 GSM pre-shrunk cotton.'
  },
  { 
    id: '14', 
    name: 'Goku Ultra Instinct Dragon Tee', 
    price: 1199, 
    originalPrice: 1799, 
    badge: 'HOT DROP', 
    graphicColor: '#F3F4F6', 
    category: 'Anime', 
    sizes: ['S', 'M', 'L', 'XL'], 
    rating: 5.0, 
    reviewsCount: 147, 
    image: '/images/IMG_5779WEB-min.webp',
    description: 'Black streetwear tee featuring white side contrast panels. The back-print showcases Goku in his mastered Ultra Instinct state backed by the legendary dragon Shenron.'
  }
];
